# Generated by Django 2.2.10 on 2020-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_meta_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='The agent name.', max_length=512),
        ),
    ]
