# Generated by Django 2.2.10 on 2020-03-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('agents', '0004_alter_agent_based_near'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place_birth',
            field=models.ForeignKey(blank=True, help_text='The location of birth of this Person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='births', to='geonames_place.Place'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_death',
            field=models.ForeignKey(blank=True, help_text='The location of death of this Person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='geonames_place.Place'),
        ),
    ]
