# Generated by Django 2.2.10 on 2020-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_unique_together_for_resource'),
        ('agents', '0006_agent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Resources that are relevant bibliographic sources.', related_name='agents', to='core.Resource'),
        ),
    ]
