# Generated by Django 2.2.10 on 2020-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_person_main_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="noble",
            field=models.BooleanField(
                default=False,
                help_text="Wether this person had a noble status at birth or not.",
            ),
        ),
    ]
