# Generated by Django 2.2.10 on 2020-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0010_person_noble"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="main_places",
            field=models.ManyToManyField(
                blank=True,
                help_text="Main places this Person is associated with (places of residence, etc.).",
                related_name="agents_main_places",
                to="geonames_place.Place",
            ),
        ),
    ]
