# Generated by Django 2.2.10 on 2020-11-26 17:26

from django.db import migrations


def merge_libraries(apps, schema_editor):
    Organisation = apps.get_model("agents", "Organisation")

    try:
        bl = Organisation.objects.get(name="BL")
        british_library = Organisation.objects.get(name="British Library")
    except Organisation.DoesNotExist:
        return

    for resource in bl.resources.all():
        british_library.resources.add(resource)

    british_library.save()
    bl.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_person_main_places"),
    ]

    operations = [
        migrations.RunPython(merge_libraries, reverse_code=migrations.RunPython.noop)
    ]
