# Generated by Django 2.2.10 on 2021-01-13 10:12

from django.db import migrations


def merge_libraries(apps, schema_editor):
    Organisation = apps.get_model("agents", "Organisation")

    try:
        libraries = Organisation.objects.filter(name="British Library").order_by("id")
        first = libraries.first()
        last = libraries.last()
    except Organisation.DoesNotExist:
        return

    for resource in last.resources.all():
        first.resources.add(resource)

    first.save()
    last.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0012_merge_libraries"),
    ]

    operations = [
        migrations.RunPython(merge_libraries, reverse_code=migrations.RunPython.noop)
    ]
