# Generated by Django 2.2.10 on 2021-01-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_merge_libraries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'given_name', 'name']},
        ),
    ]
