# Generated by Django 2.2.10 on 2021-01-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_person_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='radical',
            field=models.BooleanField(default=False, help_text='Wether this person was considered a radical or not.'),
        ),
    ]
