# Generated by Django 2.2.10 on 2021-07-08 14:02

import controlled_vocabulary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_agent_radical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='page',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='A page or document about this Agent.', related_name='_agent_page_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['viaf', 'cerl', 'wikidata']),
        ),
    ]
