# Generated by Django 2.2.28 on 2023-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0016_alter_field_page_on_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="main_places",
            field=models.ManyToManyField(
                blank=True,
                help_text="Main places this Person is associated with (places of residence, etc.).",
                related_name="agents_main_places",
                to="geonames_place.Place",
                verbose_name="other places",
            ),
        ),
    ]
