version: '3'

volumes:
  django_media: {}
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}
  #elasticsearch_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: radical_translations_dev_django
    volumes:
      - django_media:/app/radical_translations/media
    depends_on:
      - postgres
      - redis
      #- elasticsearch
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: radical_translations_dev_nginx
    volumes:
      - django_media:/usr/share/nginx/media:ro
    depends_on:
      - django

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: radical_translations_dev_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.dev/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/kdl/traefik/Dockerfile
    image: radical_translations_dev_traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - '127.0.0.1:8203:80'
    labels:
      - traefik.http.routers.web.rule='Host(`radicalt-dev.kdl.kcl.ac.uk`)'
      - traefik.http.routers.web.rule='Host(`radicalt-dev.kdl.kcl.ac.uk`) && PathPrefix(`/media/`)'

  redis:
    image: redis:5.0
  #elasticsearch:
  #image: elasticsearch:7.5.1
  #volumes:
  #- elasticsearch_data:/usr/share/elasticsearch/data
  #env_file:
  #- ./.envs/.dev/.elasticsearch
  #ports:
  #- '127.0.0.1:9200:9200'
  #- '127.0.0.1:9300:9300'
  #kibana:
  #image: kibana:7.5.1
  #depends_on:
  #- elasticsearch
  #env_file:
  #- ./.envs/.dev/.kibana
  #ports:
  #- '5601:5601'
