version: '3'

volumes:
  django_media: {}
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}
  elasticsearch_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: radical_translations_liv_django
    volumes:
      - django_media:/app/radical_translations/media
    depends_on:
      - postgres
      - redis
      - elasticsearch
    env_file:
      - ./.envs/.liv/.django
      - ./.envs/.liv/.postgres
    command: /start
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: radical_translations_liv_nginx
    volumes:
      - django_media:/usr/share/nginx/media:ro
    depends_on:
      - django
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: radical_translations_liv_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.liv/.postgres
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/liv/traefik/Dockerfile
    image: radical_translations_liv_traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - '127.0.0.1:8201:80'
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.5.1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - ./.envs/.liv/.elasticsearch
    restart: unless-stopped
  #kibana:
  #image: kibana:7.5.1
  #depends_on:
  #- elasticsearch
  #env_file:
  #- ./.envs/.liv/.kibana
  #ports:
  #- '5601:5601'
  #restart: unless-stopped
