version: '3'

volumes:
  django_media: {}
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: radical_translations_stg_django
    volumes:
      - django_media:/app/radical_translations/media
    depends_on:
      - postgres
      - redis
      - elasticsearch
    env_file:
      - ./.envs/.stg/.django
      - ./.envs/.stg/.postgres
    command: /start
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: radical_translations_stg_nginx
    volumes:
      - django_media:/usr/share/nginx/media:ro
    depends_on:
      - django
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: radical_translations_stg_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.stg/.postgres
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/stg/traefik/Dockerfile
    image: radical_translations_stg_traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - '127.0.0.1:8202:80'
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.8.1
    env_file:
      - ./.envs/.stg/.elasticsearch
    restart: unless-stopped
  #kibana:
  #image: kibana:7.5.1
  #depends_on:
  #- elasticsearch
  #env_file:
  #- ./.envs/.stg/.kibana
  #ports:
  #- '5601:5601'
  #restart: unless-stopped
