version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: radical_translations_local_django
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: radical_translations_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./.volumes/local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: radical_translations_local_node
    depends_on:
      - django
    volumes:
      - .:/app
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - ./node_modules:/app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.9.2
    env_file:
      - ./.envs/.local/.elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    restart: unless-stopped
