# Generated by Django 2.2.9 on 2020-02-03 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('geonames_place', '0004_change_meta_options_on_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='The title of the Event.', max_length=256)),
                ('date', models.OneToOneField(blank=True, help_text='The date of the Event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Date')),
                ('places', models.ManyToManyField(blank=True, help_text='The location the Event took place at.', to='geonames_place.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
