# Generated by Django 2.2.9 on 2020-02-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='related_to',
            field=models.ManyToManyField(blank=True, help_text='Resources that are related to this  Event.', related_name='events', to='core.Resource'),
        ),
    ]
