# Generated by Django 2.2.9 on 2020-02-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_related_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date__date_sort_ascending']},
        ),
    ]
