# Generated by Django 2.2.9 on 2020-02-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
