# Generated by Django 2.2.9 on 2020-02-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('events', '0005_event_meta_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='places',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, help_text='The location the Event took place at.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
        ),
    ]
