# Generated by Django 2.2.10 on 2020-05-04 12:41

import controlled_vocabulary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlled_vocabulary", "0004_remove_controlledvocabulary_test"),
        ("events", "0006_alter_event_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="classification",
            field=controlled_vocabulary.models.ControlledTermsField(
                blank=True,
                help_text="Editorial classification of the event.",
                related_name="_event_classification_+",
                to="controlled_vocabulary.ControlledTerm",
                vocabularies=["wikidata"],
            ),
        ),
    ]
