# Generated by Django 2.2.9 on 2020-02-03 15:26

import controlled_vocabulary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('utils', '0001_initial'),
        ('agents', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notes', models.TextField(blank=True, help_text='Information, usually in textual form, on attributes of a resource or some aspect of a resource.', null=True)),
                ('languages', controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Language associated with a resource or its parts.', related_name='_resource_languages_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2'])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.resource_set+', to='contenttypes.ContentType')),
                ('subjects', controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Subject term(s) describing a resource', related_name='_resource_subjects_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['fast-topic'])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('main_title', models.CharField(help_text='Title being addressed. Possible title component.', max_length=256)),
                ('subtitle', models.CharField(blank=True, help_text='Word, character, or group of words and/or characters that contains the remainder of the title after the main title. Possible title component.', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Resource')),
                ('edition_enumeration', models.CharField(blank=True, help_text='Enumeration of the edition; usually transcribed.', max_length=128, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.resource',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Resource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.resource',),
        ),
        migrations.CreateModel(
            name='ResourceRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Resource')),
                ('relationship_type', controlled_vocabulary.models.ControlledTermField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['bf-crr'])),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.ForeignKey(help_text='Title information relating to a resource: work title, preferred title, instance title, transcribed title, translated title, variant form of title, etc.', on_delete=django.db.models.deletion.CASCADE, to='core.Title'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_variant',
            field=models.ForeignKey(blank=True, help_text='Title associated with the resource that is different from the Work or Instance title (titles in another language and/or script etc.).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.Title'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('agent', models.ForeignKey(help_text='Entity associated with a resource or element of description, such as the name of the entity responsible for the content or of the publication, printing, distribution, issue, release or production of a resource.', on_delete=django.db.models.deletion.CASCADE, to='agents.Agent')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.Resource')),
                ('roles', controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Function provided by a contributor, e.g., author, illustrator, etc.', related_name='_contribution_roles_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('edition', models.CharField(help_text='Edition of the classification scheme, such as full, abridged or a number, when a classification scheme designates editions.', max_length=64)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='core.Resource')),
                ('source', models.ForeignKey(blank=True, help_text='Resource from which value or label came or was derived.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Resource')),
                ('origin_date', models.OneToOneField(blank=True, help_text='Date or date range associated with the creation of a Work.', null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Date')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.resource',),
        ),
    ]
