# Generated by Django 2.2.9 on 2020-02-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='place',
            field=models.ManyToManyField(blank=True, help_text='Geographic location or place entity associated with a resource or element of description, such as the place associated with the publication, printing, distribution, issue, release or production of a resource, place of an event.', to='geonames_place.Place'),
        ),
    ]
