# Generated by Django 2.2.9 on 2020-02-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resource_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='origin_date',
        ),
    ]
