# Generated by Django 2.2.9 on 2020-02-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('core', '0003_remove_work_origin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='place',
            new_name='places',
        ),
        migrations.AddField(
            model_name='resource',
            name='date',
            field=models.OneToOneField(blank=True, help_text='Date designation associated with a resource or element of description, such as date of title variation; year a degree was awarded; date associated with the publication, printing, distribution, issue, release or production of a resource. May be date typed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Date'),
        ),
    ]
