# Generated by Django 2.2.9 on 2020-02-04 10:11

import controlled_vocabulary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='agent',
            field=models.ForeignKey(help_text='Entity associated with a resource or element of description, such as the name of the entity responsible for the content or of the publication, printing, distribution, issue, release or production of a resource.', on_delete=django.db.models.deletion.CASCADE, related_name='contributed_to', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='related_to',
            field=models.ForeignKey(help_text='Related resource.', on_delete=django.db.models.deletion.CASCADE, to='core.Resource'),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='relationship_type',
            field=controlled_vocabulary.models.ControlledTermField(help_text='Any relationship between Work, Instance, and Item resources.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['bf-crr']),
        ),
    ]
