# Generated by Django 2.2.9 on 2020-02-04 10:47

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='edition',
            field=controlled_vocabulary.models.ControlledTermField(help_text='Edition of the classification scheme, such as full, abridged or a number, when a classification scheme designates editions.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['fast-topic']),
        ),
    ]
