# Generated by Django 2.2.10 on 2020-02-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_classification_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerelationship',
            name='related_to',
            field=models.ForeignKey(help_text='Related resource.', on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='core.Resource'),
        ),
    ]
