# Generated by Django 2.2.10 on 2020-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_meta_ordering'),
        ('core', '0011_add_held_by_and_eletronic_locator_to_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='held_by',
        ),
        migrations.AddField(
            model_name='item',
            name='held_by',
            field=models.ManyToManyField(blank=True, help_text='Entity holding the item or from which it is available.', related_name='items', to='agents.Agent'),
        ),
    ]
