# Generated by Django 2.2.10 on 2020-02-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_item_held_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="electronic_locator",
            field=models.URLField(
                blank=True,
                help_text="Electronic location from which the resource is available.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
