# Generated by Django 2.2.10 on 2020-03-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_item_electronic_locator'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='summary',
            field=models.TextField(blank=True, help_text='Description of the content of a resource, such as an abstract, summary, etc..', null=True),
        ),
    ]
