# Generated by Django 2.2.10 on 2020-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_resource_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="_is_paratext",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
