# Generated by Django 2.2.10 on 2020-03-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_instance_is_paratext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='electronic_locator',
            field=models.URLField(blank=True, help_text='Electronic location from which the resource is available.', max_length=1280, null=True),
        ),
    ]
