# Generated by Django 2.2.10 on 2020-05-01 15:32

import controlled_vocabulary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('core', '0017_alter_item_electronic_locator'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerelationship',
            name='classification',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification of the relationship.', related_name='_resourcerelationship_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata']),
        ),
    ]
