# Generated by Django 2.2.10 on 2020-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_fast_forms_to_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='summary',
            field=models.TextField(blank=True, help_text='Description of the content of a resource, such as an abstract, summary, citation, etc.', null=True),
        ),
    ]
