# Generated by Django 2.2.10 on 2020-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_field_summary_on_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='published_as',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
