# Generated by Django 2.2.10 on 2020-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contribution_published_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='published_as',
            field=models.CharField(blank=True, help_text='Name as it appears in the published resource if different from the agent name. for pseudonyms, appelations, etc.', max_length=256, null=True),
        ),
    ]
