# Generated by Django 2.2.10 on 2020-05-05 14:38

import controlled_vocabulary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_field_published_as_on_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerelationship',
            name='classification',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification.', related_name='_resourcerelationship_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata']),
        ),
    ]
