# Generated by Django 2.2.10 on 2020-05-05 14:47

import controlled_vocabulary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('core', '0023_alter_field_classification_on_resourcerelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='classification',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification.', related_name='_contribution_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata']),
        ),
    ]
