# Generated by Django 2.2.10 on 2020-05-05 15:08

import controlled_vocabulary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('core', '0024_contribution_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='languages',
        ),
        migrations.CreateModel(
            name='ResourceLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('classification', controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification.', related_name='_resourcelanguage_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata'])),
                ('language', controlled_vocabulary.models.ControlledTermField(help_text='Language associated with a resource or its parts.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['iso639-2'])),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.Resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
