# Generated by Django 2.2.10 on 2020-05-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('core', '0025_resourcelanguage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcelanguage',
            unique_together={('resource', 'language')},
        ),
    ]
