# Generated by Django 2.2.10 on 2020-05-05 15:40

import controlled_vocabulary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('core', '0026_resourcelanguage_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='places',
        ),
        migrations.CreateModel(
            name='ResourcePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('classification', controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification.', related_name='_resourceplace_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata'])),
                ('place', models.ForeignKey(help_text='Geographic location or place entity associated with a resource or element of description, such as the place associated with the publication, printing, distribution, issue, release or production of a resource, place of an event.', on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.Resource')),
            ],
            options={
                'unique_together': {('resource', 'place')},
            },
        ),
    ]
