# Generated by Django 2.2.10 on 2020-05-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_resourceplace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('main_title', 'subtitle')},
        ),
    ]
