# Generated by Django 2.2.10 on 2020-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_rbmscv_to_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Word, character, or group of words and/or characters that contains the remainder of the title after the main title. Possible title component.', max_length=256),
        ),
    ]
