# Generated by Django 2.2.10 on 2020-05-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_field_classification_on_event'),
        ('core', '0030_alter_field_subtitle_on_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
