# Generated by Django 2.2.10 on 2020-05-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_field_classification_on_event'),
        ('core', '0032_delete_instance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
