# Generated by Django 2.2.10 on 2020-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_paratext'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='edition_enumeration',
            field=models.CharField(blank=True, help_text='Enumeration of the edition; usually transcribed.', max_length=128, null=True),
        ),
    ]
