# Generated by Django 2.2.10 on 2020-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_resource_edition_enumeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='summary',
            field=models.TextField(blank=True, help_text='Description of the content of a resource, such as an abstract, summary, citation, etc.', null=True),
        ),
    ]
