# Generated by Django 2.2.10 on 2020-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_add_person_place_fields'),
        ('core', '0036_resource_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='held_by',
            field=models.ManyToManyField(blank=True, help_text='Entity holding the item or from which it is available.', related_name='resources', to='agents.Agent'),
        ),
    ]
