# Generated by Django 2.2.10 on 2020-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_resource_held_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='electronic_locator',
            field=models.URLField(blank=True, help_text='Electronic location from which the resource is available.', max_length=1280, null=True),
        ),
    ]
