# Generated by Django 2.2.10 on 2020-05-18 17:00

import controlled_vocabulary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_resource_electronic_locator'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='_is_paratext',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='resourcerelationship',
            name='relationship_type',
            field=controlled_vocabulary.models.ControlledTermField(help_text='Any relationship between resources.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['bf-crr']),
        ),
    ]
