# Generated by Django 2.2.10 on 2020-05-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_field_classification_on_event'),
        ('core', '0039_resource__is_paratext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paratext',
        ),
    ]
