# Generated by Django 2.2.10 on 2020-05-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_delete_paratext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='polymorphic_ctype',
        ),
    ]
