# Generated by Django 2.2.10 on 2020-05-26 15:19

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_resource_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='edition',
            field=controlled_vocabulary.models.ControlledTermField(help_text='Edition of the classification scheme, such as full, abridged or a number, when a classification scheme designates editions.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controlled_vocabulary.ControlledTerm', vocabularies=['rt-ppt', 'rt-tt', 'rt-pt']),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subjects',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Subject term(s) describing a resource', related_name='_resource_subjects_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['fast-forms', 'fast-topic', 'rt-agt', 'wikidata']),
        ),
    ]
