# Generated by Django 2.2.10 on 2020-07-09 16:23

import django.db.models.deletion
from django.db import migrations

import controlled_vocabulary.models


class Migration(migrations.Migration):

    dependencies = [("core", "0046_role_author_to_translator")]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="edition",
            field=controlled_vocabulary.models.ControlledTermField(
                help_text="Edition of the classification scheme, such as full, abridged or a number, when a classification scheme designates editions.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifications",
                to="controlled_vocabulary.ControlledTerm",
                vocabularies=["rt-ppt", "rt-tt", "rt-pt"],
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="roles",
            field=controlled_vocabulary.models.ControlledTermsField(
                blank=True,
                help_text="Function provided by a contributor, e.g., author, illustrator, etc.",
                related_name="contributions",
                to="controlled_vocabulary.ControlledTerm",
                vocabularies=["wikidata"],
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="subjects",
            field=controlled_vocabulary.models.ControlledTermsField(
                blank=True,
                help_text="Subject term(s) describing a resource",
                related_name="resources",
                to="controlled_vocabulary.ControlledTerm",
                vocabularies=["fast-forms", "fast-topic", "rt-agt", "wikidata"],
            ),
        ),
        migrations.AlterField(
            model_name="resourcelanguage",
            name="language",
            field=controlled_vocabulary.models.ControlledTermField(
                help_text="Language associated with a resource or its parts.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources_languages",
                to="controlled_vocabulary.ControlledTerm",
                vocabularies=["iso639-2"],
            ),
        ),
        migrations.AlterField(
            model_name="resourcerelationship",
            name="relationship_type",
            field=controlled_vocabulary.models.ControlledTermField(
                help_text="Any relationship between resources.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources_relationships",
                to="controlled_vocabulary.ControlledTerm",
                vocabularies=["bf-crr"],
            ),
        ),
    ]
