# Generated by Django 2.2.10 on 2020-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('core', '0047_alter_field_place_on_resourceplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceplace',
            name='fictional_place',
            field=models.CharField(blank=True, help_text='Name of the place if fictional.', max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resourceplace',
            unique_together={('resource', 'place', 'fictional_place')},
        ),
    ]
