# Generated by Django 2.2.10 on 2020-07-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_controlledterm_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.ForeignKey(
                help_text="Title information relating to a resource: work title, preferred title, instance title, transcribed title, translated title, variant form of title, etc.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="core.Title",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Title associated with the resource that is different from the Work or Instance title (titles in another language and/or script etc.).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_of",
                to="core.Title",
            ),
        ),
    ]
