# Generated by Django 2.2.10 on 2020-07-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_resourceplace_fictional_place'),
        ('core', '0048_title_related_names'),
    ]

    operations = [
    ]
