# Generated by Django 2.2.10 on 2020-09-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_merge_0048'),
        ('core', '0049_fast_topic_essays_to_fast_forms_essays'),
    ]

    operations = [
    ]
