# Generated by Django 2.2.10 on 2020-11-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_fast_topic_essays_to_fast_forms_essays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['resource', 'agent']},
        ),
    ]
