# Generated by Django 2.2.10 on 2020-11-13 14:47

from django.db import migrations


def copy_subjects(apps, schema_editor):
    Resource = apps.get_model("core", "Resource")

    for resource in Resource.objects.filter(classifications__edition__label="Original"):
        translations = resource.related_to.filter(
            relationship_type__label="translation of"
        )
        for translation in translations:
            for subject in translation.resource.subjects.all():
                resource.subjects.add(subject)

        resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_contribution_meta_ordering"),
    ]

    operations = [
        migrations.RunPython(copy_subjects, reverse_code=migrations.RunPython.noop)
    ]
