# Generated by Django 2.2.10 on 2020-11-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge'),
        ('core', '0050_contribution_meta_ordering'),
    ]

    operations = [
    ]
