# Generated by Django 2.2.10 on 2020-11-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20201104_1559'),
        ('core', '0051_copy_translation_subjects_to_original_resource'),
    ]

    operations = [
    ]
