# Generated by Django 2.2.10 on 2021-01-14 11:25

from django.db import migrations

from controlled_vocabulary.utils import search_term_or_none


def merge_paratext_terms(apps, schema_editor):
    Classification = apps.get_model("core", "Classification")
    ControlledTerm = apps.get_model("controlled_vocabulary", "ControlledTerm")

    vocabulary = "rt-pt"
    values = ["Community-building", "Meta-communicative", "Text-activating"]

    for v in values:
        try:
            term = ControlledTerm.objects.get(vocabulary__prefix=vocabulary, label=v)
            term_to_delete = ControlledTerm.objects.get(
                vocabulary__prefix=vocabulary, label=v.title()
            )
        except ControlledTerm.DoesNotExist:
            continue

        for c in Classification.objects.filter(edition=term_to_delete):
            c.edition = term
            c.save()

        term_to_delete.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_merge_20201113_1514"),
    ]

    operations = [
        migrations.RunPython(
            merge_paratext_terms, reverse_code=migrations.RunPython.noop
        )
    ]
