# Generated by Django 2.2.24 on 2021-10-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_edition_on_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['resource', 'agent', 'roles__label']},
        ),
    ]
