# Generated by Django 2.2.24 on 2021-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_change_meta_options_on_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
