# Generated by Django 2.2.28 on 2023-03-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_resource_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['title', 'date']},
        ),
    ]
