# Generated by Django 2.2.28 on 2023-03-16 17:23

from django.db import migrations


def copy_notes(apps, _):
    Resource = apps.get_model("core", "Resource")

    for resource in Resource.objects.all():
        resource.notes_tmp = resource.notes
        resource.save()


def reverse_copy_notes(apps, _):
    Resource = apps.get_model("core", "Resource")

    for resource in Resource.objects.all():
        resource.notes_tmp = ""
        resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_resource_notes_tmp"),
    ]

    operations = [migrations.RunPython(copy_notes, reverse_code=reverse_copy_notes)]
