# Generated by Django 2.2.28 on 2023-03-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_copy_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='notes',
        ),
    ]
