# Generated by Django 2.2.28 on 2023-03-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_resource_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='notes_tmp',
            new_name='notes',
        ),
    ]
