# Generated by Django 2.2.10 on 2020-10-12 12:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link']))], icon='doc-full-inverse')), ('featured', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link']))], icon='pick'))]),
        ),
    ]
