# Generated by Django 2.2.10 on 2020-10-13 20:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_fast_topic_essays_to_fast_forms_essays'),
        ('cms', '0006_richtextpage_to_biographypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_biography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.BiographyPage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.BlogPost'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Resource'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link']))], icon='doc-full-inverse'))], default=''),
            preserve_default=False,
        ),
    ]
