# Generated by Django 2.2.24 on 2021-11-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_eventindexpage_eventpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='url',
            new_name='event_url',
        ),
    ]
