# Generated by Django 2.2.24 on 2021-11-09 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_rename_field_url_on_eventpage_to_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 14, 55, 42, 717206, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
