name: "radicalt"

x-var: &VIRTUAL_HOST "www.radicaltranslations.org,radicaltranslations.org,radicalt-os.kdl.kcl.ac.uk,radicalt.app.cch.kcl.ac.uk,localhost,127.0.0.1"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.4
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  django:
    build:
      context: ..
      dockerfile: ./compose/production/django/Dockerfile
    restart: unless-stopped
    volumes:
      - ../volumes/media:/app/radical_translations/media
    env_file:
      - ../.envs/.django
      - ../.envs/.postgres
    command: /start
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      VIRTUAL_HOST: *VIRTUAL_HOST
      VIRTUAL_PATH: "/"
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 5000

  nginx:
    build:
      context: ..
      dockerfile: ./compose/production/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ../volumes/media:/usr/share/nginx/media:ro
    depends_on:
      - django
    environment:
      VIRTUAL_HOST: *VIRTUAL_HOST
      VIRTUAL_PATH: "~^/(media|robots.txt)/"
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 80

  postgres:
    build:
      context: ..
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
      - ../volumes/postgres_data_backups:/backups
    env_file:
      - ../.envs/.postgres
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.8.1
    env_file:
      - ../.envs/.elasticsearch
    restart: unless-stopped
