#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py autopopulate_main_menus --add-home-links
python /app/manage.py collectstatic --noinput
python /app/manage.py vocab init
python /app/manage.py search_index --rebuild -f &
python /app/manage.py zotero_import --delete &
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --timeout 180 --forwarded-allow-ips="*"
