# Generated by Django 2.2.9 on 2020-01-31 18:05

from django.db import migrations, models
import django.utils.timezone
import edtf.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_display', models.CharField(blank=True, help_text='Date in EDTF format: https://www.loc.gov/standards/datetime/', max_length=255)),
                ('date_edtf', edtf.fields.EDTFField(blank=True, lower_fuzzy_field='date_earliest', lower_strict_field='date_sort_ascending', natural_text_field='date_display', null=True, upper_fuzzy_field='date_latest', upper_strict_field='date_sort_descending')),
                ('date_earliest', models.FloatField(blank=True, null=True)),
                ('date_latest', models.FloatField(blank=True, null=True)),
                ('date_sort_ascending', models.FloatField(blank=True, null=True)),
                ('date_sort_descending', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
