# Generated by Django 2.2.9 on 2020-02-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['date_sort_ascending', 'date_sort_descending']},
        ),
    ]
