# Generated by Django 2.2.10 on 2020-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_date_meta_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='date_radical',
            field=models.CharField(blank=True, help_text='Alternative calendar date', max_length=255, null=True),
        ),
    ]
