# Generated by Django 2.2.10 on 2020-05-07 14:37

import controlled_vocabulary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('utils', '0003_date_date_radical'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='date_display_classification',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification of the display date.', related_name='_date_date_display_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata']),
        ),
        migrations.AddField(
            model_name='date',
            name='date_radical_classification',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='Editorial classification of the radical date.', related_name='_date_date_radical_classification_+', to='controlled_vocabulary.ControlledTerm', vocabularies=['wikidata']),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_radical',
            field=models.CharField(blank=True, help_text='Alternative calendar date.', max_length=255, null=True),
        ),
    ]
