# Generated by Django 2.2.10 on 2020-05-29 14:03

from django.db import migrations

from radical_translations.utils.models import get_date_radical_from_gregorian


def load_date_radical(apps, schema_editor):
    Date = apps.get_model("utils", "Date")

    for d in Date.objects.all():
        if d.date_display and not d.date_radical:
            d.date_radical = get_date_radical_from_gregorian(d.date_display)
            d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_alter_date_display_on_date"),
    ]

    operations = [
        migrations.RunPython(load_date_radical, reverse_code=migrations.RunPython.noop)
    ]
