# Generated by Django 2.2.10 on 2020-06-02 14:59

import re

from django.db import migrations


def unload_date_radical(apps, schema_editor):
    regex = re.compile(r"^\d{1,2}\s[^\s]+\san\s-?\d+")
    Date = apps.get_model("utils", "Date")

    for d in Date.objects.all():
        if d.date_radical and regex.match(d.date_radical):
            d.date_radical = None
            d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_load_date_radical"),
    ]

    operations = [
        migrations.RunPython(
            unload_date_radical, reverse_code=migrations.RunPython.noop
        )
    ]
