name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'develop']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'develop']
    paths-ignore: ['docs/**']

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Build the Stack
        run: docker-compose -f local.yml up -d --build

      - name: Run Django Tests
        run: docker-compose -f local.yml run django coverage run -m pytest -s

      - name: Tear down the Stack
        run: docker-compose -f local.yml down
